# Generated by Django 3.1.4 on 2020-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_dailytask_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('head_of_dept', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_employe', models.IntegerField(blank=True, null=True)),
                ('access_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
