# Generated by Django 3.1.4 on 2020-12-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='todolist',
            name='pending_status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='todolist',
            name='working_status',
            field=models.BooleanField(default=0),
        ),
    ]
